"""adiciona desconto_pix e destaque_promocao

Revision ID: 350200add563
Revises: 
Create Date: 2026-10-01 20:29:12.035166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '350200add563'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shirt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('desconto_pix', sa.Float(), nullable=False, server_default='10.0'))
        batch_op.add_column(sa.Column('destaque_promocao', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shirt', schema=None) as batch_op:
        batch_op.drop_column('destaque_promocao')
        batch_op.drop_column('desconto_pix')

    # ### end Alembic commands ###
