"""adiciona preco_pix_manual

Revision ID: 5ddbc9d3c536
Revises: 7aaa2ce49fc6
Create Date: 2026-10-05 16:07:33.710935

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ddbc9d3c536'
down_revision = '7aaa2ce49fc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shirt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preco_pix_manual', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shirt', schema=None) as batch_op:
        batch_op.drop_column('preco_pix_manual')

    # ### end Alembic commands ###
