"""adiciona publicado e alteracoes_pendentes

Revision ID: 7aaa2ce49fc6
Revises: 350200add563
Create Date: 2026-10-02 13:56:35.601455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7aaa2ce49fc6'
down_revision = '350200add563'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if 'configuracao' in inspector.get_table_names():
        op.drop_table('configuracao')
    with op.batch_alter_table('shirt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publicado', sa.Boolean(), nullable=False, server_default=sa.true()))
        batch_op.add_column(sa.Column('alteracoes_pendentes', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shirt', schema=None) as batch_op:
        batch_op.drop_column('alteracoes_pendentes')
        batch_op.drop_column('publicado')

    op.create_table('configuracao',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('promocao_ativa', sa.BOOLEAN(), nullable=False),
    sa.Column('promocao_percentual', sa.FLOAT(), nullable=False),
    sa.Column('promocao_categoria', sa.VARCHAR(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
