"""estoque tamanhos infantil

Revision ID: ecfceeebed57
Revises: 5ddbc9d3c536
Create Date: 2026-10-06 00:41:50.568994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ecfceeebed57'
down_revision = '5ddbc9d3c536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shirt', schema=None) as batch_op:
        batch_op.add_column(sa.Column('stock_18', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('stock_20', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('stock_22', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('stock_24', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('stock_26', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('stock_28', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shirt', schema=None) as batch_op:
        batch_op.drop_column('stock_28')
        batch_op.drop_column('stock_26')
        batch_op.drop_column('stock_24')
        batch_op.drop_column('stock_22')
        batch_op.drop_column('stock_20')
        batch_op.drop_column('stock_18')

    # ### end Alembic commands ###
